-- Deprecated.
--
-- Do not run one-off RLS repair snippets for this maintained fork.
-- The supported backend setup is the canonical idempotent migration:
--
--   supabase/migrations/20260614062844_recreate_flowfit_backend.sql
--
-- Follow the current recovery runbook instead:
--
--   docs/SUPABASE_RECOVERY_RUNBOOK.md
